# Generated by python -m scripts.n_gamma.manufactured; do not edit.
"""Scalar Numba evaluators of the manufactured data in ``forcing.py``, for compiled pointwise coefficients.

Every function is ``@njit(cache=True)`` and takes scalars ``(x, y, s)`` in the
case frame (``x = R - 3`` for the axisymmetric geometry). ``b_p`` returns the
pair ``(b_1, b_2)``. ``S_n`` and ``S_Gamma`` select the geometry and
stationarity with ``variant = VARIANTS.index((geometry, stationary))``;
stationary variants ignore ``s``. Call them from module-level functions (not
closures) so Numba's cache holds.
"""
import math

from numba import njit

VARIANTS = (("cartesian", False), ("cartesian", True), ("axisymmetric", False), ("axisymmetric", True))

@njit(cache=True)
def n_e(x, y, s):
    v0 = math.pi*y
    v1 = math.pi*x
    return -1/10*math.sin(s - v0)*math.cos(s + 2*v1) - 1/5*math.sin(s - v1)*math.cos(2*s + v0) + 2


@njit(cache=True)
def u_e(x, y, s):
    v0 = math.pi*x
    v1 = math.pi*y
    return -1/10*math.sin(s - 2*v0)*math.cos(3*s + v1) - 2/5*math.sin(s - v1)*math.cos(2*s + v0) + 1/5


@njit(cache=True)
def Gamma_e(x, y, s):
    v0 = math.pi*y
    v1 = math.sin(s - v0)
    v2 = math.pi*x
    v3 = 2*v2
    v4 = 2*s
    return (-1/10*v1*math.cos(s + v3) - 1/5*math.sin(s - v2)*math.cos(v0 + v4) + 2)*(-2/5*v1*math.cos(v2 + v4) - 1/10*math.sin(s - v3)*math.cos(3*s + v0) + 1/5)


@njit(cache=True)
def b_p(x, y, s):
    v0 = 1/math.sqrt(x**2 + y**2 + 1)
    return -v0*y, v0*x


@njit(cache=True)
def _S_n_transient_cartesian(x, y, s):
    v0 = math.pi*x
    v1 = 2*v0
    v2 = s + v1
    v3 = math.sin(v2)
    v4 = math.pi*y
    v5 = s - v4
    v6 = math.sin(v5)
    v7 = math.cos(v5)
    v8 = math.cos(v2)
    v9 = (1/10)*v8
    v10 = v7*v9
    v11 = s - v0
    v12 = math.sin(v11)
    v13 = 2*s
    v14 = v13 + v4
    v15 = math.sin(v14)
    v16 = math.cos(v11)
    v17 = (1/5)*math.cos(v14)
    v18 = v16*v17
    v19 = (1/5)*math.pi
    v20 = math.pi*v18 + v19*v3*v6
    v21 = x**2
    v22 = y**2
    v23 = v21 + v22 + 1
    v24 = 1/v23
    v25 = (1/50)*v24
    v26 = math.pi*v10 + v12*v15*v19
    v27 = math.pi**2
    v28 = (1/5)*v27
    v29 = v6*v9
    v30 = v12*v17
    v31 = v27*v30
    v32 = (2/5)*v6
    v33 = 3*s + v4
    v34 = math.cos(v33)
    v35 = s - v1
    v36 = (1/10)*math.sin(v35)
    v37 = v0 + v13
    v38 = math.cos(v37)
    v39 = -v32*v38 - v34*v36 + 1/5
    v40 = 1/math.sqrt(v23)
    v41 = v40*y
    v42 = -v29 - v30 + 2
    return -v10 + (2/5)*v12*v15 - v18 - v20*v25*x - v20*v39*v41 - 1/25*v24*x*y*(-v15*v16*v28 - v28*v3*v7) - v25*v26*y + v26*v39*v40*x + (1/10)*v3*v6 + v40*v42*x*(math.pi*v36*math.sin(v33) + (2/5)*math.pi*v38*v7) - v41*v42*(v19*v34*math.cos(v35) + math.pi*v32*math.sin(v37)) - (-v21*v25 + 1/50)*(v27*v29 + v31) - (-v22*v25 + 1/50)*(v27*v32*v8 + v31)


@njit(cache=True)
def _S_Gamma_transient_cartesian(x, y, s):
    v0 = math.pi*y
    v1 = s - v0
    v2 = math.sin(v1)
    v3 = math.pi*x
    v4 = 2*v3
    v5 = s + v4
    v6 = math.sin(v5)
    v7 = v2*v6
    v8 = (1/5)*math.pi
    v9 = s - v3
    v10 = math.cos(v9)
    v11 = 2*s
    v12 = v0 + v11
    v13 = (1/5)*math.cos(v12)
    v14 = v10*v13
    v15 = math.pi*v14 + v7*v8
    v16 = x**2
    v17 = y**2
    v18 = v16 + v17 + 1
    v19 = 1/math.sqrt(v18)
    v20 = v19*y
    v21 = v15*v20
    v22 = math.cos(v1)
    v23 = math.cos(v5)
    v24 = (1/10)*v23
    v25 = v22*v24
    v26 = math.sin(v9)
    v27 = math.sin(v12)
    v28 = v26*v27
    v29 = math.pi*v25 + v28*v8
    v30 = s - v4
    v31 = math.sin(v30)
    v32 = 3*s + v0
    v33 = math.cos(v32)
    v34 = (1/10)*v33
    v35 = v31*v34
    v36 = v11 + v3
    v37 = math.cos(v36)
    v38 = (2/5)*v37
    v39 = v2*v38
    v40 = -v35 - v39 + 1/5
    v41 = v40**2
    v42 = v2*v24
    v43 = v13*v26
    v44 = -v42 - v43 + 2
    v45 = math.sin(v32)
    v46 = v31*v45
    v47 = math.sin(v36)
    v48 = v2*v47
    v49 = (4/5)*v48
    v50 = math.cos(v30)
    v51 = v22*v38
    v52 = v33*v50
    v53 = (2/5)*math.pi
    v54 = v48*v53 + v52*v8
    v55 = 1/v18
    v56 = (3/100)*v55
    v57 = (1/10)*math.pi*v46 + math.pi*v51
    v58 = math.pi**2
    v59 = v39*v58
    v60 = v43*v58
    v61 = (2/5)*v58
    v62 = (1/5)*v58
    return v19*v29*v41*x + v19*v29*x + v19*v40*v44*x*((4/5)*math.pi*v22*v37 + v46*v8) - v20*v40*v44*(math.pi*v49 + v52*v53) - v21*v41 - v21 + v40*(-v14 - v25 + (2/5)*v28 + (1/10)*v7) + v44*(-v34*v50 + (3/10)*v46 + v49 - v51) - 3/50*v55*x*y*(v15*v57 + v29*v54 + v40*(-v10*v27*v62 - v22*v6*v62) + v44*(-v22*v47*v61 - v45*v50*v62)) - v56*x*(v15*v40 + v44*v54) - v56*y*(v29*v40 + v44*v57) - (-v16*v56 + 3/100)*(2*v29*v57 + v40*(v42*v58 + v60) + v44*(v35*v58 + v59)) - (-v17*v56 + 3/100)*(2*v15*v54 + v40*(v2*v23*v61 + v60) + v44*(v31*v33*v61 + v59))


@njit(cache=True)
def _S_n_stationary_cartesian(x, y, s):
    v0 = math.pi*x
    v1 = math.cos(v0)
    v2 = math.pi*y
    v3 = math.cos(v2)
    v4 = 2*v0
    v5 = math.sin(v4)
    v6 = math.pi*v5
    v7 = math.sin(v2)
    v8 = (1/5)*v7
    v9 = (1/5)*math.pi*v1*v3 - v6*v8
    v10 = x**2
    v11 = y**2
    v12 = v10 + v11 + 1
    v13 = 1/v12
    v14 = (1/50)*v13
    v15 = math.sin(v0)
    v16 = math.pi*v15
    v17 = math.cos(v4)
    v18 = -v16*v8 + (1/10)*math.pi*v17*v3
    v19 = math.pi**2
    v20 = (1/5)*v3
    v21 = v15*v20
    v22 = v19*v21
    v23 = (1/10)*v7
    v24 = v17*v23
    v25 = (2/5)*v7
    v26 = v21 + v24 + 2
    v27 = 1/math.sqrt(v12)
    v28 = v27*y
    v29 = v1*v25 + (1/10)*v3*v5 + 1/5
    return -1/25*v13*x*y*(-v1*v19*v8 - v19*v20*v5) - v14*v18*y - v14*v9*x + v18*v27*v29*x + v26*v27*x*((2/5)*math.pi*v1*v3 - v23*v6) - v26*v28*(-v16*v25 + (1/5)*math.pi*v17*v3) - v28*v29*v9 - (-v10*v14 + 1/50)*(-v19*v24 - v22) - (-v11*v14 + 1/50)*(-v17*v19*v25 - v22)


@njit(cache=True)
def _S_Gamma_stationary_cartesian(x, y, s):
    v0 = math.pi*x
    v1 = math.cos(v0)
    v2 = math.pi*y
    v3 = math.cos(v2)
    v4 = math.sin(v2)
    v5 = math.pi*v4
    v6 = 2*v0
    v7 = math.sin(v6)
    v8 = (1/5)*v7
    v9 = v5*v8
    v10 = (1/5)*math.pi*v1*v3 - v9
    v11 = x**2
    v12 = y**2
    v13 = v11 + v12 + 1
    v14 = 1/math.sqrt(v13)
    v15 = v14*y
    v16 = v10*v15
    v17 = math.sin(v0)
    v18 = (1/5)*v17
    v19 = math.cos(v6)
    v20 = -v18*v5 + (1/10)*math.pi*v19*v3
    v21 = (2/5)*v1*v4
    v22 = (1/10)*v7
    v23 = v22*v3
    v24 = v21 + v23 + 1/5
    v25 = v24**2
    v26 = v17*v5
    v27 = v18*v3
    v28 = (1/10)*v19*v4
    v29 = v27 + v28 + 2
    v30 = (1/5)*math.pi*v19*v3 - 2/5*v26
    v31 = 1/v13
    v32 = (3/100)*v31
    v33 = (2/5)*math.pi*v1*v3 - v22*v5
    v34 = math.pi**2
    v35 = v27*v34
    v36 = v21*v34
    v37 = (2/5)*v34
    v38 = v19*v4
    v39 = v3*v37
    v40 = (1/5)*v34
    return v14*v20*v25*x + v14*v20*x + v14*v24*v29*x*((4/5)*math.pi*v1*v3 - v9) - v15*v24*v29*((2/5)*math.pi*v19*v3 - 4/5*v26) - v16*v25 - v16 - 3/50*v31*x*y*(v10*v33 + v20*v30 + v24*(-v1*v4*v40 - v3*v34*v8) + v29*(-v17*v39 - v38*v40)) - v32*x*(v10*v24 + v29*v30) - v32*y*(v20*v24 + v29*v33) - (-v11*v32 + 3/100)*(2*v20*v33 + v24*(-v28*v34 - v35) + v29*(-v23*v34 - v36)) - (-v12*v32 + 3/100)*(2*v10*v30 + v24*(-v35 - v37*v38) + v29*(-v36 - v39*v7))


@njit(cache=True)
def _S_n_transient_axisymmetric(x, y, s):
    v0 = math.pi*x
    v1 = 2*v0
    v2 = s + v1
    v3 = math.sin(v2)
    v4 = math.pi*y
    v5 = s - v4
    v6 = math.sin(v5)
    v7 = math.cos(v5)
    v8 = math.cos(v2)
    v9 = (1/10)*v8
    v10 = v7*v9
    v11 = s - v0
    v12 = math.sin(v11)
    v13 = 2*s
    v14 = v13 + v4
    v15 = math.sin(v14)
    v16 = math.cos(v11)
    v17 = (1/5)*math.cos(v14)
    v18 = v16*v17
    v19 = x**2
    v20 = y**2
    v21 = v19 + v20 + 1
    v22 = (1/50)/v21
    v23 = (1/5)*math.pi
    v24 = math.pi*v18 + v23*v3*v6
    v25 = v24*x
    v26 = (1/25)/v21**2
    v27 = v20*v25*v26
    v28 = math.pi*v10 + v12*v15*v23
    v29 = v19*v26*v28*y
    v30 = math.pi**2
    v31 = (1/5)*v30
    v32 = v22*y
    v33 = v32*x*(-v15*v16*v31 - v3*v31*v7)
    v34 = v6*v9
    v35 = v12*v17
    v36 = v30*v35
    v37 = -v34 - v35 + 2
    v38 = 3*s + v4
    v39 = math.cos(v38)
    v40 = s - v1
    v41 = (1/10)*math.sin(v40)
    v42 = v0 + v13
    v43 = math.cos(v42)
    v44 = (2/5)*v6
    v45 = -v39*v41 - v43*v44 + 1/5
    v46 = v37*v45*x*y/v21**(3/2)
    v47 = 1/math.sqrt(v21)
    v48 = x + 3
    v49 = v28*v32
    v50 = -v20*v22 + 1/50
    v51 = v47*y
    v52 = v45*v51
    return -v10 + (2/5)*v12*v15 - v18 - v22*v25 + v27 + v28*v45*v47*x - v29 + (1/10)*v3*v6 - v33 + v37*v47*x*(math.pi*v41*math.sin(v38) + (2/5)*math.pi*v43*v7) - v46 - (-v19*v22 + 1/50)*(v30*v34 + v36) + (-v24*v50 - v37*v52 + v48*(-v24*v52 - v27 + v29 - v33 - v37*v51*(v23*v39*math.cos(v40) + math.pi*v44*math.sin(v42)) + v46 - v49 - v50*(v30*v44*v8 + v36)) - v49*x)/v48


@njit(cache=True)
def _S_Gamma_transient_axisymmetric(x, y, s):
    v0 = x + 3
    v1 = x**2
    v2 = y**2
    v3 = v1 + v2 + 1
    v4 = 1/math.sqrt(v3)
    v5 = v4*y
    v6 = math.pi*y
    v7 = s - v6
    v8 = math.sin(v7)
    v9 = math.pi*x
    v10 = 2*v9
    v11 = s + v10
    v12 = math.cos(v11)
    v13 = (1/10)*v12
    v14 = v13*v8
    v15 = s - v9
    v16 = math.sin(v15)
    v17 = 2*s
    v18 = v17 + v6
    v19 = (1/5)*math.cos(v18)
    v20 = v16*v19
    v21 = -v14 - v20 + 2
    v22 = s - v10
    v23 = math.sin(v22)
    v24 = 3*s + v6
    v25 = math.cos(v24)
    v26 = (1/10)*v25
    v27 = v23*v26
    v28 = v17 + v9
    v29 = math.cos(v28)
    v30 = (2/5)*v29
    v31 = v30*v8
    v32 = -v27 - v31 + 1/5
    v33 = v32**2
    v34 = v21*v33
    v35 = math.sin(v24)
    v36 = v23*v35
    v37 = math.cos(v7)
    v38 = v30*v37
    v39 = (1/10)*math.pi*v36 + math.pi*v38
    v40 = v13*v37
    v41 = math.sin(v18)
    v42 = v16*v41
    v43 = (1/5)*math.pi
    v44 = math.pi*v40 + v42*v43
    v45 = v21*v39 + v32*v44
    v46 = (3/100)/v3
    v47 = v46*y
    v48 = v45*v47
    v49 = -v2*v46 + 3/100
    v50 = math.sin(v11)
    v51 = v50*v8
    v52 = math.cos(v15)
    v53 = v19*v52
    v54 = v43*v51 + math.pi*v53
    v55 = math.sin(v28)
    v56 = v55*v8
    v57 = (2/5)*math.pi
    v58 = math.cos(v22)
    v59 = v25*v58
    v60 = v43*v59 + v56*v57
    v61 = v21*v60 + v32*v54
    v62 = math.pi**2
    v63 = (2/5)*v62
    v64 = v31*v62
    v65 = v20*v62
    v66 = v5*v54
    v67 = (1/5)*v62
    v68 = v47*x*(v21*(-v35*v58*v67 - v37*v55*v63) + v32*(-v37*v50*v67 - v41*v52*v67) + v39*v54 + v44*v60)
    v69 = (4/5)*v56
    v70 = v21*v32
    v71 = (3/50)/v3**2
    v72 = v61*x
    v73 = -v1*v45*v71*y + v2*v71*v72 - v34*x*y/v3**(3/2)
    v74 = v4*x
    v75 = v44*v74
    return v21*(-v26*v58 + (3/10)*v36 - v38 + v69) + v32*(-v40 + (2/5)*v42 + (1/10)*v51 - v53) + v33*v75 - v46*v72 - v66 - v68 + v70*v74*((4/5)*math.pi*v29*v37 + v36*v43) + v73 + v75 - (-v1*v46 + 3/100)*(v21*(v27*v62 + v64) + v32*(v14*v62 + v65) + 2*v39*v44) + (v0*(-v33*v66 - v48 - v49*(v21*(v23*v25*v63 + v64) + v32*(v12*v63*v8 + v65) + 2*v54*v60) - v5*v70*(v57*v59 + math.pi*v69) - v68 - v73) - v34*v5 - v48*x - v49*v61)/v0


@njit(cache=True)
def _S_n_stationary_axisymmetric(x, y, s):
    v0 = x**2
    v1 = y**2
    v2 = v0 + v1 + 1
    v3 = (1/50)/v2
    v4 = math.pi*x
    v5 = math.cos(v4)
    v6 = math.pi*y
    v7 = math.cos(v6)
    v8 = 2*v4
    v9 = math.sin(v8)
    v10 = math.sin(v6)
    v11 = math.pi*v10
    v12 = v11*v9
    v13 = -1/5*v12 + (1/5)*math.pi*v5*v7
    v14 = v13*x
    v15 = (1/25)/v2**2
    v16 = v1*v14*v15
    v17 = math.sin(v4)
    v18 = (1/5)*v17
    v19 = math.cos(v8)
    v20 = -v11*v18 + (1/10)*math.pi*v19*v7
    v21 = v0*v15*v20*y
    v22 = math.pi**2
    v23 = v3*y
    v24 = v23*x*(-1/5*v10*v22*v5 - 1/5*v22*v7*v9)
    v25 = v18*v7
    v26 = v22*v25
    v27 = v10*v19
    v28 = (1/10)*v27
    v29 = v25 + v28 + 2
    v30 = (2/5)*v10
    v31 = v30*v5 + (1/10)*v7*v9 + 1/5
    v32 = v29*v31*x*y/v2**(3/2)
    v33 = 1/math.sqrt(v2)
    v34 = x + 3
    v35 = v20*v23
    v36 = -v1*v3 + 1/50
    v37 = v33*y
    v38 = v29*v37
    return -v14*v3 + v16 + v20*v31*v33*x - v21 - v24 + v29*v33*x*(-1/10*v12 + (2/5)*math.pi*v5*v7) - v32 - (-v0*v3 + 1/50)*(-v22*v28 - v26) + (-v13*v36 - v31*v38 + v34*(-v13*v31*v37 - v16 + v21 - v24 + v32 - v35 - v36*(-2/5*v22*v27 - v26) - v38*(-math.pi*v17*v30 + (1/5)*math.pi*v19*v7)) - v35*x)/v34


@njit(cache=True)
def _S_Gamma_stationary_axisymmetric(x, y, s):
    v0 = math.pi*x
    v1 = math.cos(v0)
    v2 = math.pi*y
    v3 = math.cos(v2)
    v4 = math.sin(v2)
    v5 = (1/5)*v4
    v6 = 2*v0
    v7 = math.sin(v6)
    v8 = math.pi*v7
    v9 = v5*v8
    v10 = (1/5)*math.pi*v1*v3 - v9
    v11 = x**2
    v12 = y**2
    v13 = v11 + v12 + 1
    v14 = 1/math.sqrt(v13)
    v15 = v14*y
    v16 = v10*v15
    v17 = math.sin(v0)
    v18 = math.pi*v17
    v19 = math.cos(v6)
    v20 = -v18*v5 + (1/10)*math.pi*v19*v3
    v21 = (1/5)*v3
    v22 = v17*v21
    v23 = v19*v4
    v24 = (1/10)*v23
    v25 = v22 + v24 + 2
    v26 = (2/5)*v4
    v27 = v1*v26
    v28 = v3*v7
    v29 = (1/10)*v28
    v30 = v27 + v29 + 1/5
    v31 = v30**2
    v32 = v25*v31
    v33 = v32*x*y/v13**(3/2)
    v34 = (3/100)/v13
    v35 = -v18*v26 + (1/5)*math.pi*v19*v3
    v36 = v10*v30 + v25*v35
    v37 = v36*x
    v38 = (3/50)/v13**2
    v39 = v12*v37*v38
    v40 = (2/5)*math.pi*v1*v3 - 1/10*v4*v8
    v41 = v20*v30 + v25*v40
    v42 = v11*v38*v41*y
    v43 = math.pi**2
    v44 = v22*v43
    v45 = v27*v43
    v46 = (2/5)*v43
    v47 = v34*y
    v48 = v47*x*(v10*v40 + v20*v35 + v25*(-v17*v3*v46 - 1/5*v23*v43) + v30*(-v1*v43*v5 - v21*v43*v7))
    v49 = x + 3
    v50 = v41*v47
    v51 = -v12*v34 + 3/100
    return v14*v20*v31*x + v14*v20*x + v14*v25*v30*x*((4/5)*math.pi*v1*v3 - v9) - v16 - v33 - v34*v37 + v39 - v42 - v48 - (-v11*v34 + 3/100)*(2*v20*v40 + v25*(-v29*v43 - v45) + v30*(-v24*v43 - v44)) + (-v15*v32 - v36*v51 + v49*(-v15*v25*v30*(-4/5*v18*v4 + (2/5)*math.pi*v19*v3) - v16*v31 + v33 - v39 + v42 - v48 - v50 - v51*(2*v10*v35 + v25*(-v28*v46 - v45) + v30*(-v23*v46 - v44))) - v50*x)/v49


@njit(cache=True)
def S_n(x, y, s, variant):
    """S_n of variant VARIANTS[variant]."""
    if variant == 0:
        return _S_n_transient_cartesian(x, y, s)
    if variant == 1:
        return _S_n_stationary_cartesian(x, y, s)
    if variant == 2:
        return _S_n_transient_axisymmetric(x, y, s)
    return _S_n_stationary_axisymmetric(x, y, s)


@njit(cache=True)
def S_Gamma(x, y, s, variant):
    """S_Gamma of variant VARIANTS[variant]."""
    if variant == 0:
        return _S_Gamma_transient_cartesian(x, y, s)
    if variant == 1:
        return _S_Gamma_stationary_cartesian(x, y, s)
    if variant == 2:
        return _S_Gamma_transient_axisymmetric(x, y, s)
    return _S_Gamma_stationary_axisymmetric(x, y, s)
