"""Regenerate continuous n–Gamma manufactured data (SymPy is optional).

Run ``python -m scripts.n_gamma.manufactured`` from the checkout to write
``cases/forcing.py`` (NumPy/CuPy) and ``cases/forcing_numba.py`` (scalar Numba
evaluators for compiled pointwise coefficients), or add ``--check`` to detect
drift without writing. No solver or time integration runs.
"""
from __future__ import annotations

import argparse
from pathlib import Path


HEADER = '''# Generated by python -m scripts.n_gamma.manufactured; do not edit.
"""Continuous manufactured fields and forcing, independent of discretization.

The exact fields, b_p and P are functions of (x, y). The sources need an
explicit geometry (no default): "cartesian" uses the plain divergence with
(x, y) the mesh coordinates; "axisymmetric" uses the axisymmetric divergence
with x=R-3 and y=Z. Scalars and broadcastable NumPy/CuPy arrays are accepted.
Vector/tensor components occupy trailing axes. Set stationary=True to freeze
s=0 AND remove time derivatives. These sources are unweighted; the ADR
builder multiplies them by the measure weight (1 or R).
"""
from __future__ import annotations

import numpy as np

D = 0.02
MU = 0.03
C_S = 1.0
GEOMETRIES = ("cartesian", "axisymmetric")


def _check_geometry(geometry):
    if geometry not in GEOMETRIES:
        raise ValueError(f"geometry must be one of {GEOMETRIES}; got {geometry!r}")


def _arguments(x, y, t, xp):
    if xp is None:
        if any(hasattr(a, "__cuda_array_interface__") for a in (x, y, t)):
            import cupy
            xp = cupy
        else:
            xp = np
    return xp.asarray(x), xp.asarray(y), xp.asarray(t), xp

'''


NUMBA_HEADER = '''# Generated by python -m scripts.n_gamma.manufactured; do not edit.
"""Scalar Numba evaluators of the manufactured data in ``forcing.py``, for compiled pointwise coefficients.

Every function is ``@njit(cache=True)`` and takes scalars ``(x, y, s)`` in the
case frame (``x = R - 3`` for the axisymmetric geometry). ``b_p`` returns the
pair ``(b_1, b_2)``. ``S_n`` and ``S_Gamma`` select the geometry and
stationarity with ``variant = VARIANTS.index((geometry, stationary))``;
stationary variants ignore ``s``. Call them from module-level functions (not
closures) so Numba's cache holds.
"""
import math

from numba import njit

VARIANTS = (("cartesian", False), ("cartesian", True), ("axisymmetric", False), ("axisymmetric", True))

'''


def symbolic_expressions():
    """Return independently differentiated symbolic continuous PDE data."""
    import sympy as sp

    x, y, s = sp.symbols("x y s", real=True)
    pi = sp.pi
    n = (2 + sp.Rational(1, 5)*sp.sin(pi*x-s)*sp.cos(pi*y+2*s)
         + sp.Rational(1, 10)*sp.cos(2*pi*x+s)*sp.sin(pi*y-s))
    u = (sp.Rational(1, 5) + sp.Rational(2, 5)*sp.cos(pi*x+2*s)*sp.sin(pi*y-s)
         + sp.Rational(1, 10)*sp.sin(2*pi*x-s)*sp.cos(pi*y+3*s))
    gamma = n*u
    q = 1+x*x+y*y
    b = sp.Matrix([-y, x])/sp.sqrt(q)
    p = sp.eye(2)-b*b.T

    def grad(f):
        return sp.Matrix([sp.diff(f, x), sp.diff(f, y)])

    def divergence(f, geometry):
        if geometry == "cartesian":
            return sp.diff(f[0], x)+sp.diff(f[1], y)
        return sp.diff((x+3)*f[0], x)/(x+3)+sp.diff(f[1], y)

    expressions = {"n_e": n, "u_e": u, "Gamma_e": gamma, "b_p": list(b), "P": list(p)}
    for geometry in ("cartesian", "axisymmetric"):
        spatial_n = divergence(gamma*b-sp.Rational(1, 50)*p*grad(n), geometry)
        spatial_gamma = divergence(n*u*u*b-sp.Rational(3, 100)*p*grad(gamma), geometry)+b.dot(grad(n))
        expressions.update({
            f"S_n_transient_{geometry}": sp.diff(n, s)+spatial_n,
            f"S_Gamma_transient_{geometry}": sp.diff(gamma, s)+spatial_gamma,
            # Freeze before code generation; stationary time derivatives are zero.
            f"S_n_stationary_{geometry}": spatial_n.subs(s, 0),
            f"S_Gamma_stationary_{geometry}": spatial_gamma.subs(s, 0),
        })
    return expressions


def render_module() -> str:
    """Produce deterministic, CSE-reduced NumPy/CuPy source text."""
    import sympy as sp
    from sympy.printing.pycode import pycode

    def code(expression):
        return pycode(expression).replace("math.", "xp.")

    sections = [HEADER]
    for name, expression in symbolic_expressions().items():
        exprs = expression if isinstance(expression, list) else [expression]
        replacements, reduced = sp.cse(exprs, symbols=sp.numbered_symbols("v"))
        lines = [f"def _{name}(x, y, s, xp):"]
        lines += [f"    {symbol} = {code(value)}" for symbol, value in replacements]
        if name in ("b_p", "P"):
            lines += ["    components = xp.broadcast_arrays(" + ", ".join(map(code, reduced)) + ")",
                      "    result = xp.stack(components, axis=-1)"]
            lines += ["    return result.reshape(result.shape[:-1] + (2, 2))" if name == "P" else "    return result"]
        else:
            lines += [f"    return {code(reduced[0])}"]
        sections.append("\n".join(lines)+"\n\n\n")

    for name in ("n_e", "u_e", "Gamma_e", "b_p", "P", "S_n", "S_Gamma"):
        stationary_arg = "" if name in ("b_p", "P") else "stationary=False, "
        if name.startswith("S_"):
            stationary_arg = "geometry, " + stationary_arg
        description = {
            "n_e": "Exact density; stationary=True freezes the phase at zero.",
            "u_e": "Exact parallel velocity; stationary=True freezes the phase at zero.",
            "Gamma_e": "Exact momentum n_e*u_e; stationary=True freezes the phase at zero.",
            "b_p": "Poloidal magnetic components (...,2), without renormalization; t is ignored.",
            "P": "Perpendicular projector (...,2,2), I-b_p*b_p.T; t is ignored.",
            "S_n": "Continuous density source for geometry 'cartesian' or 'axisymmetric'; "
                   "stationary=True also removes the time derivative.",
            "S_Gamma": "Continuous momentum source including pressure for geometry 'cartesian' or "
                       "'axisymmetric'; stationary=True removes the time derivative.",
        }[name]
        lines = [f"def {name}(x, y, t=0.0, *, {stationary_arg}xp=None):",
                 f'    """{description}"""',
                 "    x, y, t, xp = _arguments(x, y, t, xp)"]
        if name.startswith("S_"):
            lines += ["    _check_geometry(geometry)", '    if geometry == "cartesian":',
                      "        if stationary:",
                      f"            return _{name}_stationary_cartesian(x, y, 0.0, xp)",
                      f"        return _{name}_transient_cartesian(x, y, t, xp)",
                      "    if stationary:",
                      f"        return _{name}_stationary_axisymmetric(x, y, 0.0, xp)",
                      f"    return _{name}_transient_axisymmetric(x, y, t, xp)"]
        else:
            time = "t" if name in ("b_p", "P") else "0.0 if stationary else t"
            lines += [f"    return _{name}(x, y, {time}, xp)"]
        sections.append("\n".join(lines)+"\n\n\n")
    return "".join(sections).rstrip()+"\n"


def render_numba_module() -> str:
    """Produce deterministic, CSE-reduced scalar ``math`` source text compiled with Numba."""
    import sympy as sp
    from sympy.printing.pycode import pycode

    sections = [NUMBA_HEADER]
    expressions = symbolic_expressions()
    for name, expression in expressions.items():
        if name == "P":
            continue
        exprs = expression if isinstance(expression, list) else [expression]
        replacements, reduced = sp.cse(exprs, symbols=sp.numbered_symbols("v"))
        public = name in ("n_e", "u_e", "Gamma_e", "b_p")
        lines = ["@njit(cache=True)", f"def {'' if public else '_'}{name}(x, y, s):"]
        lines += [f"    {symbol} = {pycode(value)}" for symbol, value in replacements]
        lines += [f"    return {', '.join(map(pycode, reduced))}"]
        sections.append("\n".join(lines)+"\n\n\n")
    variants = [("cartesian", "transient"), ("cartesian", "stationary"),
                ("axisymmetric", "transient"), ("axisymmetric", "stationary")]
    for name in ("S_n", "S_Gamma"):
        lines = ["@njit(cache=True)", f"def {name}(x, y, s, variant):",
                 f'    """{name} of variant VARIANTS[variant]."""']
        for index, (geometry, kind) in enumerate(variants[:-1]):
            lines += [f"    if variant == {index}:", f"        return _{name}_{kind}_{geometry}(x, y, s)"]
        lines += [f"    return _{name}_{variants[-1][1]}_{variants[-1][0]}(x, y, s)"]
        sections.append("\n".join(lines)+"\n\n\n")
    return "".join(sections).rstrip()+"\n"


def main(argv=None):
    """Write the committed evaluator module, or check it with --check."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if committed evaluators differ")
    args = parser.parse_args(argv)
    directory = Path(__file__).with_name("cases")
    try:
        rendered = {directory / "forcing.py": render_module(), directory / "forcing_numba.py": render_numba_module()}
    except ModuleNotFoundError as error:
        if error.name != "sympy":
            raise
        parser.error("Install the generator extra: python -m pip install -e '.[manufactured]'")
    if args.check:
        if any(not path.exists() or path.read_text() != text for path, text in rendered.items()):
            parser.exit(1, "Manufactured evaluator drift; regenerate with python -m scripts.n_gamma.manufactured\n")
    else:
        directory.mkdir(parents=True, exist_ok=True)
        for path, text in rendered.items():
            path.write_text(text)


if __name__ == "__main__":
    main()
